import React from 'react';
import Head from 'next/head';
import {
  BaseButton,
  BaseSubtitle,
  BaseTitle,
  Layout,
  NavbarLink,
} from '../components';
import styles from './Home.module.scss';
import Strawberry from '../assets/img/Strawberry';
import Grapefruit from '../assets/img/Grapefruit';
import Leftgroup from '../assets/img/Leftgroup';
import Rightgroup from '../assets/img/Rightgroup';

export default function Home() {
  const [auth, setAuth] = React.useState(false);
  const [recordValue, setRecordValue] = React.useState(1300);

  return (
    <Layout>
      <div className={styles.Grapefruit}>
        <Grapefruit />
      </div>

      <div className={styles.Strawberry}>
        <Strawberry />
      </div>

      <div className={styles.Leftgroup}>
        <Leftgroup />
      </div>

      <div className={styles.Rightgroup}>
        <Rightgroup />
      </div>

      <div className={styles.MainContent}>
        <Head>
          <title>THE BODY SHOP</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.Main}>
          <BaseTitle first_title='Настроение' second_title='мягкости' />
          <BaseSubtitle
            subtitle='Помоги котику собрать
ингредиенты из новой коллекции
масел для тела «The Body Shop»'
            style={{ marginBottom: 24 }}
          />
          <BaseButton style={{ minWidth: 210, marginBottom: 16 }}>
            Играть
          </BaseButton>

          {auth ? (
            <div className={styles.Record}>
              Рекорд: <span>{recordValue}</span>
            </div>
          ) : (
            <NavbarLink href='auth' title='Войти' />
          )}
        </main>
      </div>
    </Layout>
  );
}
