import React from 'react';
import Head from 'next/head';
import {
  BaseButton,
  BaseSubtitle,
  BaseTitle,
  Layout,
  NavbarLink,
} from '../components';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.scss';
import Strawberry from '../assets/img/Strawberry';
import Grapefruit from '../assets/img/Grapefruit';
import Leftgroup from '../assets/img/Leftgroup';
import Rightgroup from '../assets/img/Rightgroup';
import LogoImg from '../assets/img/LogoImg';

import LogoText from '../assets/img/LogoText';
import DesktopTopLeft from '../assets/img/DesktopTopLeft';
import DesktopTopRight from '../assets/img/DesktopTopRight';
import DesktopBotLeft from '../assets/img/DesktopBotLeft';
import DesktopBotRight from '../assets/img/DesktopBotRight';
import QrCode from '../assets/img/QrCode';

import { isMobile } from 'react-device-detect';

export default function Home() {
  const [auth, setAuth] = React.useState(false);
  const [recordValue, setRecordValue] = React.useState(1300);

  const router = useRouter();

  React.useEffect(() => {
    const testEmail = window.localStorage.getItem('email');
    const testPassword = window.localStorage.getItem('phone');
    if (testEmail && testPassword) {
      setAuth(true);
    }
  }, []);

  return (
    <Layout>
      <Grapefruit className={styles.Grapefruit} />

      <Strawberry className={styles.Strawberry} />

      <Leftgroup className={styles.Leftgroup} />

      <Rightgroup className={styles.Rightgroup} />

      <div className={styles.MainContent}>
        <Head>
          <title>THE BODY SHOP</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.Main}>
          <div className={styles.Main__logoImg}>
            <LogoImg />
          </div>
          <BaseTitle
            style={{ marginBottom: 15, fontSize: 14, lineHeight: '200%' }}
          >
            Замур-р-рчательные
            <br />
            <span className={styles.Main_largetitle}>баттеры</span>
          </BaseTitle>
          <BaseSubtitle style={{ marginBottom: 24 }}>
            Помоги котику собрать <br /> ингредиенты из новой коллекции <br />{' '}
            масел для тела «The Body Shop»
          </BaseSubtitle>
          <BaseButton
            style={{ marginBottom: 16 }}
            method={() => router.push('/game')}
          >
            Играть
          </BaseButton>
          {auth ? (
            <div className={styles.Record}>
              Рекорд: <span>{recordValue}</span>
            </div>
          ) : (
            <NavbarLink href='/Auth' title='Войти' />
          )}
        </main>
      </div>
    </Layout>
    // <>
    //   {!isMobile ? (
    //     <Layout>
    //       <Grapefruit className={styles.Grapefruit} />

    //       <Strawberry className={styles.Strawberry} />

    //       <Leftgroup className={styles.Leftgroup} />

    //       <Rightgroup className={styles.Rightgroup} />

    //       <div className={styles.MainContent}>
    //         <Head>
    //           <title>THE BODY SHOP</title>
    //           <meta name='description' content='Generated by create next app' />
    //           <link rel='icon' href='/favicon.ico' />
    //         </Head>

    //         <main className={styles.Main}>
    //           <div className={styles.Main__logoImg}>
    //             <LogoImg />
    //           </div>
    //           <BaseTitle
    //             style={{ marginBottom: 15, fontSize: 14, lineHeight: '200%' }}
    //           >
    //             Замур-р-рчательные
    //             <br />
    //             <span className={styles.Main_largetitle}>баттеры</span>
    //           </BaseTitle>
    //           <BaseSubtitle style={{ marginBottom: 24 }}>
    //             Помоги котику собрать <br /> ингредиенты из новой коллекции{' '}
    //             <br /> масел для тела «The Body Shop»
    //           </BaseSubtitle>
    //           <BaseButton
    //             style={{ marginBottom: 16 }}
    //             method={() => router.push('/game')}
    //           >
    //             Играть
    //           </BaseButton>
    //           {auth ? (
    //             <div className={styles.Record}>
    //               Рекорд: <span>{recordValue}</span>
    //             </div>
    //           ) : (
    //             <NavbarLink href='/Auth' title='Войти' />
    //           )}
    //         </main>
    //       </div>
    //     </Layout>
    //   ) : (
    //     <>
    //       <div className={styles.Desktop}>
    //         <DesktopTopLeft className={styles.DesktopTopLeft} />
    //         <DesktopTopRight className={styles.DesktopTopRight} />
    //         <DesktopBotLeft className={styles.DesktopBotLeft} />
    //         <DesktopBotRight className={styles.DesktopBotRight} />

    //         <div className={styles.Desktop_content}>
    //           <LogoImg className={styles.Desktop_logoimg} />
    //           <LogoText className={styles.Desktop_logotext} />
    //           <QrCode className={styles.Desktop_qrcode} />

    //           <BaseTitle style={{ marginBottom: 16, lineHeight: '200%' }}>
    //             <span className={styles.mini}>Настроение</span>
    //             <br />
    //             <span className={styles.large}>мягкости</span>
    //           </BaseTitle>

    //           <BaseSubtitle>
    //             Помоги котику собрать ингредиенты из новой <br /> коллекции
    //             масел для тела «The Body Shop». <br />
    //             <br />
    //             Для участия в акции открой <br />
    //             мобильную версию.
    //           </BaseSubtitle>
    //         </div>
    //       </div>
    //     </>
    //   )}
    // </>
  );
}
